# Generated by Django 5.2.7 on 2025-11-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitproject', '0002_profile_goal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DfitUser',
            new_name='Account',
        ),
    ]
