# Generated by Django 5.2.7 on 2025-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitproject', '0003_rename_dfituser_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
