# Generated by Django 5.2.7 on 2025-11-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitproject', '0004_profile_joined_date_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trainer_required',
        ),
    ]
